# Bae image
FROM python:3.11-slim

# System libs: PortAudio runtime + ALSA
RUN apt-get update && apt-get install -y --no-install-recommends \
      alsa-utils \
      libportaudio2 libasound2 \
    && rm -rf /var/lib/apt/lists/*

# Python deps
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# App
COPY . /app
WORKDIR /app


CMD ["python", "wledAR.py"]