# Bae image
FROM python:3.11-slim

# System libs: PortAudio runtime + ALSA
RUN apt-get update && apt-get install -y --no-install-recommends \
      alsa-utils \
      libportaudio2 libasound2 \
    && rm -rf /var/lib/apt/lists/*

# Non-root user
RUN useradd -ms /bin/bash app
USER app
WORKDIR /home/app

# Python deps
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# App
COPY main.py .

# Default envs (can be overridden by compose)
ENV INPUT_DEVICE=hw:Loopback,1,0 \
    SAMPLE_RATE=44100 \
    FRAME_SIZE=1024 \
    WLED_HOST=192.168.50.123 \
    WLED_PORT=21324

CMD ["python", "main.py"]