# Bae image
FROM python:3.11-slim

# System libs: PortAudio + ALSA + sndfile + basic tools for debugging
RUN apt-get update && apt-get install -y --no-install-recommends \
      libportaudio2 libportaudiocpp0 \
      libasound2 libasound2-data libasound2-plugins \
      libsndfile1 \
      alsa-utils procps iproute2 tcpdump ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Python deps
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# App
COPY . /app
WORKDIR /app


CMD ["python", "-u", "wledAR2.py"]