services:

  audio-bridge:
      image: debian:stable-slim
      network_mode: host
      privileged: true              # for modprobe (or cap_add: [SYS_MODULE])
      devices:
        - /dev/snd:/dev/snd
      environment:
        IN_PCM:  "hw:Loopback,1,0"      # read from tap
        OUT_PCM: "plughw:BossDAC,0"     # write to DAC (format-safe)
        RATE:    "44100"
        PERIOD:  "256"
        FRAGS:   "3"
      command: >
        sh -c '
          modprobe snd-aloop index=9 id=Loopback pcm_substreams=2 || true;
          for i in $(seq 1 60); do [ -e /proc/asound/Loopback ] && break; sleep 0.3; done;
          apt-get update && apt-get install -y --no-install-recommends alsa-utils;
          exec alsaloop -C "$IN_PCM" -P "$OUT_PCM" -r "$RATE" -p "$PERIOD" -n "$FRAGS"
        '
      restart: unless-stopped

  bluetooth:
    build: ./blue
    container_name: bluetooth
    depends_on: [audio-bridge]
    restart: unless-stopped
    network_mode: host
    privileged: true
    devices:
      - /dev/snd
    volumes:
     - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket:ro
    environment:
      ALSA_OUT: "hw:Loopback,0,0"   # write into tap
      BLUEALSA_PROFILES: "a2dp-sink"

  audio-processor:
    build: ./pyaudio
    container_name: audio-processor
    depends_on: [audio-bridge]
    restart: unless-stopped   
    network_mode: host
    devices:
      - /dev/snd
    # volumes:
    environment:
      INPUT_DEVICE: "hw:Loopback,1,0"   # read from tap (same as audio-bridge input)
      SAMPLE_RATE: "44100"
      FRAME_SIZE: "1024"
      WLED_HOST: "192.168.50.123"
      WLED_PORT: "21324"
 
