services:

  bluetooth:
    build: ./blue
    container_name: bluetooth
    network_mode: host
    restart: unless-stopped
    # privileged: true
    # devices:
    #   - /dev/snd
    volumes:
     - /etc/bluetooth:/conf
     - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket:ro
    environment:
     - BT_MAC=C6:EE:74:B2:BD:18
    

  # app:
  #   build: ./app
  #   container_name: app
  #   network_mode: host
  #   restart: unless-stopped
  #   privileged: true
  #   devices:
  #   volumes:
  #   environment: