services:

  bluetooth:
    build: ./blue
    container_name: bluetooth
    restart: unless-stopped
    network_mode: host
    privileged: true
    # devices:
    #   - /dev/snd
    volumes:
     - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket:ro
    # environment:

    

  # app:
  #   build: ./app
  #   container_name: app
  #   network_mode: host
  #   restart: unless-stopped
  #   privileged: true
  #   devices:
  #   volumes:
  #   environment: