# Base image
FROM debian:bookworm-slim

# Install necessary packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    bluez bluez-tools dbus rfkill \
 && rm -rf /var/lib/apt/lists/*

# Set working directory and copy entrypoint script onto host
WORKDIR /app
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# Run the entrypoint script on startup
ENTRYPOINT ["/usr/bin/env", "bash", "/usr/local/bin/entrypoint.sh"]